const cards = [
  {
    id: 1,
    name: "Maria Andres",
    location: " Loc: Obere Str.57",
    city: "Berlin",
    salary: "Salary: $5000/month",
    job: "Designer",
    email: "Email: andresmaria@gmail.com",
    img: "images/profile1.jpg",
  },
  {
    id: 2,
    name: "Ana Trujilio",
    location: "Loc: Matderos 2312 ",
    city: "City: Mexico D.F",
    salary: "Salary: $3500/month",
    job: "Job: Designer web",
    email: "Email: anatruji54@gmail.yahoo",
    img: "images/profile2.jpg",
  },
  {
    id: 3,
    name: "Antonia Moreno",
    location: " Location: Manoria Str.2312",
    city: "City: Dothan",
    salary: "Salary: $7500/month",
    job: "Job: Enginner",
    email: "Email: antoniomoreno@gmail.yahoo",
    img: "images/profile3.jpg",
  },
  {
    id: 4,
    name: "Frank Gerald",
    location: " Location:Bachfross Str.89",
    city: "City: Harrison",
    salary: "Salary: $52889/month",
    job: "Job: Enginner",
    email: "Email: frank@gmail.yahoo",
    img: "images/profile4.jpg",
  },
  {
    id: 5,
    name: "Rachel Green",
    location: " Location: Los Angeles",
    city: "City:Califronia ",
    salary: "Salary: $5890/month",
    job: "Job: Enginner",
    email: "Email: green64@gmail.yahoo",
    img: "images/profile5.jpg",
  },
  {
    id: 6,
    name: "Ricky Park",
    location: " Location: America",
    city: "City: New York",
    salary: "Salary: $5000/month",
    job: "Job: Enginner",
    email: "Email: ricky_park@yahoo.com",
    img: "images/profile6.jpg",
  },
  {
    id: 7,
    name: "Emma Charles",
    location: " Location: WoumansRow Str.67",
    city: "City:Frankfurt",
    salary: "Salary: $7000/month",
    job: "Job: Enginner pro",
    email: "Email:emmacharles@yahoo.com ",
    img: "images/profile7.jpg",
  },
  {
    id: 8,
    name: "Martin Jeffrins",
    location: " Location:  Str.67",
    city: "City: New York",
    salary: "Salary: $258000/month",
    job: "Job: Driver",
    email: "Email:debora_56@yahoo.com",
    img: "images/profile8.jpg",
  },
  {
    id: 9,
    name: "Lopez Naggy",
    location: " Location: California",
    city: "City: Los Angeles",
    salary: "Salary: $5000/month",
    job: "Job: Enginner consultant",
    email: "Email: naggy_98k@yahoo.com",
    img: "images/profile9.jpg",
  },
  {
    id: 10,
    name: "Elisabeth Crownwell",
    location: " Location: Romania",
    city: "Sebes",
    salary: "Salary: $8000/month",
    job: "Job: web developer",
    email: "Email:elisa_87 @yahoo.com",
    img: "images/profile10.jpg",
  },
];

export default cards;
