const cards = [
  {
    id: 1,
    name: "Ricky Park",
    location: " Location: America",
    city: "City: New York",
    salary: "Salary: $5000/month",
    job: "Job: Enginner",
    email: "Email: ricky_park@yahoo.com",
    img: "./images/rrrrr.jpg",
  },
  {
    id: 1,
    name: "Ricky Park",
    location: " Location: America",
    city: "City: New York",
    salary: "Salary: $5000/month",
    job: "Job: Enginner",
    email: "Email: ricky_park@yahoo.com",
    img: "./girl2.jpg",
  },
  {
    id: 1,
    name: "Ricky Park",
    location: " Location: America",
    city: "City: New York",
    salary: "Salary: $5000/month",
    job: "Job: Enginner",
    email: "Email: ricky_park@yahoo.com",
  },
  {
    id: 1,
    name: "Ricky Park",
    location: " Location: America",
    city: "City: New York",
    salary: "Salary: $5000/month",
    job: "Job: Enginner",
    email: "Email: ricky_park@yahoo.com",
  },
  {
    id: 1,
    name: "Ricky Park",
    location: " Location: America",
    city: "City: New York",
    salary: "Salary: $5000/month",
    job: "Job: Enginner",
    email: "Email: ricky_park@yahoo.com",
  },
  {
    id: 1,
    name: "Ricky Park",
    location: " Location: America",
    city: "City: New York",
    salary: "Salary: $5000/month",
    job: "Job: Enginner",
    email: "Email: ricky_park@yahoo.com",
  },
  {
    id: 1,
    name: "Ricky Park",
    location: " Location: America",
    city: "City: New York",
    salary: "Salary: $5000/month",
    job: "Job: Enginner",
    email: "Email: ricky_park@yahoo.com",
  },
];

export default cards;
