const cards = [
  {
    id: 1,
    name: "Ricky Park",
    location: " Location: America",
    city: "City: New York",
    salary: "Salary: $5000/month",
    job: "Job: Enginner",
    email: "Email: ricky_park@yahoo.com",
    img: "images/rrrrr.jpg",
  },
  {
    id: 2,
    name: "Ricky Park",
    location: " Location: America",
    city: "City: New York",
    salary: "Salary: $5000/month",
    job: "Job: Enginner",
    email: "Email: ricky_park@yahoo.com",
    img: "images/girl2.jpg",
  },
  {
    id: 3,
    name: "Ricky Park",
    location: " Location: America",
    city: "City: New York",
    salary: "Salary: $5000/month",
    job: "Job: Enginner",
    email: "Email: ricky_park@yahoo.com",
  },
  {
    id: 4,
    name: "Ricky Park",
    location: " Location: America",
    city: "City: New York",
    salary: "Salary: $5000/month",
    job: "Job: Enginner",
    email: "Email: ricky_park@yahoo.com",
  },
  {
    id: 5,
    name: "Ricky Park",
    location: " Location: America",
    city: "City: New York",
    salary: "Salary: $5000/month",
    job: "Job: Enginner",
    email: "Email: ricky_park@yahoo.com",
  },
  {
    id: 6,
    name: "Ricky Park",
    location: " Location: America",
    city: "City: New York",
    salary: "Salary: $5000/month",
    job: "Job: Enginner",
    email: "Email: ricky_park@yahoo.com",
  },
  {
    id: 7,
    name: "Ricky Park",
    location: " Location: America",
    city: "City: New York",
    salary: "Salary: $5000/month",
    job: "Job: Enginner",
    email: "Email: ricky_park@yahoo.com",
  },
];

export default cards;
